export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const SUCCESSFULLY_LOGGED_IN = 'SUCCESSFULLY_LOGGED_IN';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const STARTING_LOGIN = 'STARTING_LOGIN';
